#!/bin/bash

echo '      	      .andAHHAbnn.`  '
echo '           .aAHHHAAUUAAHHHAn.   '
echo '          dHP^~"        "~^THb.  '
echo '    .   .AHF                YHA.   .'
echo '    |  .AHHb.              .dHHA.  |'
echo '    |  HHAUAAHAbn      adAHAAUAHA  |'
echo '    I  HF~"_____        ____ ]HHH  I'
echo '   HHI HAPK""~^YUHb  dAHHHHHHHHHH IHH'
echo '   HHI HHHD> .andHH  HHUUP^~YHHHH IHH'
echo '   YUI ]HHP     "~Y  P~"     THH[ IUP'
echo '    "  `HK                   ]HH`  " '
echo '        THAn.  .d.aAAn.b.  .dHHP     '
echo '        ]HHHHAAUP" ~~ "YUAAHHHH[     '
echo '        `HHP^~"  .annn.  "~^YHH`      '
echo '         YHb    ~" "" "~    dHF       '
echo '          "YAb..abdHHbndbndAP"        '
echo '           THHAAb.  .adAHHF           '
echo '            "UHHHHHHHHHHU"            '
echo '              ]HHUUHHHHHH[            ' 
echo '            .adHHb "HHHHHbn.           '
echo '     ..andAAHHHHHHb.AHHHHHHHAAbnn..    ' 
echo '.ndAAHHHHHHUUHHHHHHHHHHUP^~"~^YUHHHAAbn. '
echo '  "~^YUHHP"   "~^YUHHUP"        "^YUP^"  '
echo '       ""         "~~"                  '
echo '                                            '
echo ' ______   ______     ______     __   __     ______     ______     ______     ______  '  
echo '/\__  _\ /\  ___\   /\  ___\   /\ "-.\ \   /\  __ \   /\  == \   /\  __ \   /\__  _\ '
echo '\/_/\ \/ \ \  __\   \ \ \____  \ \ \-.  \  \ \ \/\ \  \ \  __<   \ \ \/\ \  \/_/\ \/ '
echo '   \ \_\  \ \_____\  \ \_____\  \ \_\\"\_\  \ \_____\  \ \_____\  \ \_____\    \ \_\ '
echo '    \/_/   \/_____/   \/_____/   \/_/ \/_/   \/_____/   \/_____/   \/_____/     \/_/ '


sleep 3
echo 'Tiempo de hoy:'
date +"%H:%M:%S"
